### ISSUE TITLE
missing screenshot in elisp/tests

### ISSUE THREAD

**Issue by brandelune** [exercism/elisp#101]
The link to the screenshot is not valid:
https://x.exercism.io/v3/tracks/elisp/docs/img/dual-pane.png

**Comment by vermiculus** [comment]
Where are you seeing this link?

**Comment by brandelune** [comment]
here:
https://exercism.io/tracks/elisp/tests

In the last paragraph: Suggestions

**Comment by vermiculus** [comment]
Thanks! Opened a PR.
