### ISSUE TITLE
Mentoring request

### ISSUE THREAD

**Issue by PhilHudson** [exercism/elisp#105]
I've had an exercise stuck in feedback limbo for a month.

**Comment by benreyn** [comment]
@PhilHudson, first I would like to apologize not only for the fact that you have had solutions stuck in the feedback / mentoring phase for so long, but also that you felt the only recourse you had was to open an issue here. 

I don't tend to do nearly as much mentoring on the track as I should, and do my best to field the Pull Requests here, as well as adding a new exercise here and there when I have the time.

The upcoming week is a very busy one for me personally, so I hope that some of the elisp mentors can help work through the backlog. I have shared this in the elisp mentors slack channel in hopes that someone there can get to it before my schedule clears up. 

Again, I am so very sorry that this was your experience with exercism, and I intend to do everything in my power to help remedy that.

**Comment by benreyn** [comment]
Thanks @xuchunyang! Your a saint! 👍

**Comment by benreyn** [comment]
@PhilHudson, can I close this issue? I think our backlog got cleaned out.

**Comment by PhilHudson** [comment]
Sorry to take so long in my turn. Forgot to enable notifications. Thanks for resolving my issue.
