### ISSUE TITLE
Run ERT test in batch mode without leaving Emacs

### ISSUE THREAD

**Issue by xuchunyang** [exercism/elisp#120]
I notice some students are not using the batch mode, because if they do, they will notice the test won't pass due to missing requires and incorrect way to turn on `lexical-binding`, although the test does pass under some certain conditions.

Maybe it is not very easy to type that long command in the command line, for example, I usually need to goto `(info "(ert) Running Tests in Batch Mode")` to find out the function name `ert-run-tests-batch-and-exit`. https://exercism.io/tracks/elisp/tests suggests creating a shell wrapper, however I think it is easier to create an Emacs command:

```el
(defun exercism-elisp-test ()
  "Run Emacs Lisp test in current directory."
  (interactive)
  (shell-command
   "emacs --batch -l *-test.el -f ert-run-tests-batch-and-exit"))
```

**Comment by vermiculus** [comment]
Instructions on running the tests this way would be good to include in the README template at least; that's where it's most relevant.

If we go the route of providing any support code, it's probably most appropriate to release that code as a package and publish to MELPA. That way, we could suggest installing the package in the README template then using that.

The package itself would be very simple to start – probably just a post-save hook on elisp buffers where the file name is in `(expand-file-name "elisp" (string-trim-right (shell-command-to-string "exercism workspace") "\\n"))`. Buffer-save would give a visual overall pass/fail (modeline color?) and provide context on cue.

What do you think?

**Comment by xuchunyang** [comment]
I would like it to be mentioned in https://github.com/exercism/elisp/blob/master/docs/TESTS.md

**Comment by vermiculus** [comment]
I don't think folks are necessarily looking at TESTS.md often – not beyond the first one or two exercises. I for example had no idea existed [for Rust](https://exercism.io/tracks/rust/tests); I was going purely off what was in the README:

> <img width="506" alt="image" src="https://user-images.githubusercontent.com/2082195/58427204-95cf8180-8064-11e9-9c1c-5042408bd929.png">

Probably the basic `emacs --batch -l *-test.el -f ert-run-tests-batch-and-exit` should be sufficient for this page – we can shunt the other ways to run tests into TESTS.md. As for that file, we can organize it better to promote the batch job. I imagine folks are reading the first few lines and saying 'ah yes, `M-x ert RET t` is easy to remember and just *does everything*; I'll use that'. While ERT is a robust framework, we don't need to describe *all* the ways to invoke it.

**Comment by xuchunyang** [comment]
Another reason people don't want use the batch mode is that they're using third part libraries such as dash.el and s.el.

I usually have to use the batch mode to run the ERT tests because sometimes I forget if the functions' definitions are latest unless I hit <kbd>C-M-x</kbd> (`eval-defun`) one by one.

I probably just want to share the little command, if I work through the elisp track now, I prefer the emacs command to the shell command.

**Comment by vermiculus** [comment]
> Another reason people don't want use the batch mode is that they're using third part libraries such as dash.el and s.el.

Why would this preclude using the batch command?

---

Also, you should check out `eval-buffer`.

**Comment by xuchunyang** [comment]
> Why would this preclude using the batch command?

They'll have to figure how to make these third party libraries available through the command line, e.g.,

    emacs --batch -L /Users/xcy/.emacs.d/elpa-26.2/dash-20190424.1804/ -l *-test.el -f ert-run-tests-batch-and-exit



> Also, you should check out `eval-buffer`.

Thanks. I have `defvar` and `defun` mixed up.

**Comment by vermiculus** [comment]
Your original function would in fact be prone to this as well; to get around that, you'd need to run the following:

    emacs --batch --eval "(progn (require 'package) (package-initialize))" -l *-test.el -f ert-run-tests-batch-and-exit
