### ISSUE TITLE
Multiple luhn tests wrong

### ISSUE THREAD

**Issue by PhilHudson** [exercism/elisp#125]
Unless I've either completely misunderstood the requirement, or completely misimplemented it -- both possible, of course, even probable -- at least 3 of the tests in `luhn-test.el` are wrong. Two of them (`a-valid-3-digit-input-that-can-be-reversed` and `an-invalid-3-digit-input`) involve input strings "059" (should fail, test expects success) and "095" (should pass, test expects fail). The third mistaken test I've identified is `an-invalid-11-digit-number`.

**Comment by yurrriq** [comment]
Thanks for pointing this out. Perhaps you can create and issue re: https://github.com/exercism/problem-specifications/blob/f375a46c1e3d50ecd0347ab1dfc8bbdafc8817c7/exercises/luhn/canonical-data.json

**Comment by PhilHudson** [comment]
Forked problem-specifications intending to do a quick edit and submit
a PR, but found that the data in exercises/luhn/canonical-data.json
bear little resemblance to what's in the tests in the Elisp exercise
-- nothing matches all three of "description" "input" and "expected".
I guess the Elisp exercise was generated from some earlier version, in
which case I guess this can't be resolved and can be closed WONTFIX or
whatever we use for such cases.

On 11/08/2019, Eric Bailey <notifications@github.com> wrote:
> Thanks for pointing this out. Perhaps you can create and issue re:
> https://github.com/exercism/problem-specifications/blob/f375a46c1e3d50ecd0347ab1dfc8bbdafc8817c7/exercises/luhn/canonical-data.json
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/exercism/elisp/issues/125#issuecomment-520200323


-- 
phil.hudson@iname.com                      PGP/GnuPG ID: 0x887DCA63

**Comment by yurrriq** [comment]
Ah, I see. Would you be interested to updating the elisp tests then?
