### ISSUE TITLE
Mark all but the first test as pending in exercises?

### ISSUE THREAD

**Issue by Trevoke** [exercism/elisp#47]
The standard behavior in exercism tracks, to help simulate TDD, is to mark all but the first test as pending.

In ert, it [looks like](http://emacs.stackexchange.com/questions/12400/pending-test-in-ert) this can be done with `(ert-skip "pending")` or maybe `:expected-result :failed` ?

**Comment by yurrriq** [comment]
I don't follow this strategy personally, so I'll leave it up to the community to comment here.

**Comment by yurrriq** [comment]
Does anyone else have any comments?
