### ISSUE TITLE
Track maintainer?

### ISSUE THREAD

**Issue by benjamreynolds** [exercism/elisp#73]
Is this track still maintained? Im noticing #61 doesnt have alot of activity on it.

**Comment by yurrriq** [comment]
Volunteers welcome/wanted! It might be just me, and I’m rather busy these days.

**Comment by benjamreynolds** [comment]
Would love to pitch in where I can and help get elisp ready for v2!

**Comment by benjamreynolds** [comment]
Going to close this, because I think I got the answer to my question. I plan to add more exercises and help work on #46 as I go along.
